server:
  port: 8001

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loyalty-program-balances-service?currentSchema=public
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/loyalty-program-balances-service?currentSchema=public
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
